"use client";

import * as React from "react";
import { Edit } from "lucide-react";
import { useTranslations } from "next-intl";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Checkbox } from "@/components/ui/checkbox";
import { cn } from "@/lib/utils";
import { formatSuggestedPrice } from "../utils/format-price";
import type { ImportItemDto, ImportVariantDraft } from "../types/admin-catalog.types";

const MAX_VISIBLE_VARIANTS = 3;

function ImportVariantList({ variants }: { variants: ImportVariantDraft[] }) {
  const t = useTranslations("admin-catalog");
  const visible = variants.slice(0, MAX_VISIBLE_VARIANTS);
  const remaining = variants.length - MAX_VISIBLE_VARIANTS;

  return (
    <div className="border-t border-slate-100 mt-3 pt-3 space-y-1.5">
      {variants.length === 0 ? (
        <p className="text-xs text-slate-400">{t("variants.noVariants")}</p>
      ) : (
        <>
          {visible.map((v, i) => (
            <div key={i} className="flex items-center justify-between gap-2 text-xs">
              <span className="text-slate-600 truncate">{v.variantLabel}</span>
              <span className="font-semibold text-slate-900 shrink-0">
                {formatSuggestedPrice(v.suggestedPrice)}
              </span>
            </div>
          ))}
          {remaining > 0 && (
            <p className="text-xs text-slate-400">
              {t("variants.moreVariants", { count: remaining })}
            </p>
          )}
        </>
      )}
    </div>
  );
}

interface ImportItemCardProps {
  item: ImportItemDto;
  isSelected: boolean;
  onToggleSelect: (id: string) => void;
  onEdit: (item: ImportItemDto) => void;
}

function getItemStatus(item: ImportItemDto): "duplicate" | "auto" | "ready" {
  if (item.suggestedGlobalProductId) return "duplicate";
  if (item.sku?.startsWith("IMP-")) return "auto";
  return "ready";
}

export function ImportItemCard({ item, isSelected, onToggleSelect, onEdit }: ImportItemCardProps) {
  const t = useTranslations("admin-catalog");
  const tCommon = useTranslations("common");
  const status = getItemStatus(item);

  return (
    <div
      className={cn(
        "group relative bg-white rounded-xl border flex flex-col h-full transition-all duration-200 overflow-hidden",
        isSelected
          ? "border-indigo-400 ring-1 ring-indigo-300"
          : "border-slate-200 hover:border-slate-300",
        !isSelected && "opacity-80"
      )}
    >
      {/* Image */}
      <div className="aspect-4/3 bg-slate-100 relative overflow-hidden">
        {item.imageUrl ? (
          <img
            src={item.imageUrl}
            alt={item.name}
            className="w-full h-full object-cover transition-transform duration-300 group-hover:scale-105"
            onError={(e) => {
              (e.target as HTMLImageElement).src =
                "https://placehold.co/400x300/e2e8f0/64748b";
            }}
          />
        ) : (
          <div className="w-full h-full flex items-center justify-center">
            <span className="text-slate-400 text-sm">{tCommon("status.noImage")}</span>
          </div>
        )}

        {/* Status badge top-left */}
        <div className="absolute top-2 left-2">
          {status === "duplicate" && (
            <Badge className="text-xs bg-yellow-100 text-yellow-800 hover:bg-yellow-100 border-yellow-300">
              {t("possibleDuplicate")}
            </Badge>
          )}
          {status === "auto" && (
            <Badge variant="secondary" className="text-xs bg-slate-100 text-slate-600 hover:bg-slate-100">
              {t("autoGenerated")}
            </Badge>
          )}
          {status === "ready" && (
            <Badge className="text-xs bg-green-100 text-green-700 hover:bg-green-100 border-green-300">
              {t("importItemStatus.ready")}
            </Badge>
          )}
        </div>

        {/* Checkbox top-right */}
        <div className="absolute top-2 right-2 bg-white/90 rounded p-0.5">
          <Checkbox
            checked={isSelected}
            onCheckedChange={() => onToggleSelect(item.id)}
            aria-label={item.name}
          />
        </div>

      </div>

      {/* Content */}
      <div className="p-4 flex flex-col flex-1">
        {item.sku && (
          <p className="text-xs font-mono text-slate-500 mb-1">{item.sku}</p>
        )}

        <h3 className="font-semibold text-slate-900 line-clamp-2 mb-1">{item.name}</h3>

        <div className="flex items-center gap-2 mb-2 flex-wrap">
          {item.brand && (
            <span className="text-xs text-slate-600 bg-slate-100 px-2 py-0.5 rounded">
              {item.brand}
            </span>
          )}
          {item.rawCategory && (
            <span className="text-xs text-indigo-600 bg-indigo-50 px-2 py-0.5 rounded">
              {item.rawCategory}
            </span>
          )}
        </div>

        {item.suggestedGlobalProductId && item.suggestedGlobalProductName && (
          <p className="text-xs text-yellow-700 mb-1 truncate">
            {t("duplicateOf", { name: item.suggestedGlobalProductName })}
          </p>
        )}

        {/* Variants — takes remaining space, pushing footer down */}
        <div className="flex-1">
          <ImportVariantList variants={item.variants ?? []} />
        </div>

        {/* Footer */}
        <div className="pt-3 border-t border-slate-100 mt-3">
          <Button
            variant="ghost"
            size="sm"
            className="w-full text-slate-600 hover:text-indigo-700"
            onClick={() => onEdit(item)}
          >
            <Edit className="w-3.5 h-3.5 mr-1.5" />
            {tCommon("buttons.edit")}
          </Button>
        </div>
      </div>
    </div>
  );
}
